spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor
    username: root
    password: admin
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true

  #for swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher